FROM archlinux
LABEL maintainer="jberenguer.dev@gmail.com"

ARG repohost
RUN echo "Server = http://${repohost}/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist

RUN pacman -Sy --noconfirm <package>

RUN useradd <> && mkhomedir_helper <>

WORKDIR /home/<>
USER <>

ENTRYPOINT ["/path/command","arg"]
